### ISSUE TITLE
How to get Recommendation in Views ?

### ISSUE THREAD

**Issue by stripathi669** [fcurella/django-recommends#16]
Hi,

I have two doubts:

1. How do  I get recommendation in views.py, given I have the user instance ?
2. How do I generate recommendation without waiting 24 hours, in case I want to check whether everything went allright ?

Thanks

**Comment by fcurella** [comment]
Hi @stripathi669,

1. You can get a user's recommentation by querying the `Recommendation` model: `Recommendation.objects.filter(user=user)`. See http://django-recommends.readthedocs.org/en/latest/models.html#Recommendation
2. You can change the compute interval by overriding the `RECOMMENDS_TASK_CRONTAB` setting. See http://django-recommends.readthedocs.org/en/latest/settings.html#celery-task

**Comment by stripathi669** [comment]
Hi,

Thanks for blazin fast reply. 
When I implement this:

    from recommends.storages.djangoorm.models import Recommendation
    Recommendation.objects.filter(user=user)

In views, it throws HTTP 500 error. I can see Similarity table populated in Admin, but recommendation table is empty.
What could be possibly cause of this error ?

**Comment by fcurella** [comment]
Can you post the stracktrace from the view? Please use the 'switch to copy and past view' button on the Django default error page

**Comment by stripathi669** [comment]
My Bad. I passed user object instead pk.
Thanks

**Comment by stripathi669** [comment]
But why is Recommendation table always empty ? Even though similarity table is populated. I have plenty of users, vote and products.

**Comment by fcurella** [comment]
It could be something on your RecommendationProvider.

You can check if it's running the `store_recommendations` by setting the loglevel of the `recommends` logger to INFO and looking at the output (see https://docs.djangoproject.com/en/1.7/topics/logging/#configuring-logging)

**Comment by stripathi669** [comment]
I did what you suggested, and here's the log for that:

[2015-03-18 10:21:38,583: INFO/Worker-7] calculating similarities...
[2015-03-18 10:21:38,741: INFO/Worker-7] saving similarities...
[2015-03-18 10:21:38,742: INFO/Worker-7] saving similarities
[2015-03-18 10:22:16,020: INFO/Worker-7] saved 12968 similarities...
[2015-03-18 10:22:16,338: INFO/Worker-7] fetching ignored items...
[2015-03-18 10:22:16,339: INFO/Worker-7] saving recommendations...
[2015-03-18 10:22:16,359: INFO/Worker-7] saving recommendations
[2015-03-18 10:22:16,359: INFO/Worker-7] saved 0 recommendations...

Hence store_recommendations is being called. It's just that it's empty, which means calculate_recommendations is returning empty list.

**Comment by fcurella** [comment]
Hi @stripathi669 

I'm not sure if you figured out your issue or you need more help. Let me know if I can close this issue.

Thanks

**Comment by stripathi669** [comment]
Yes, It is working for me now.

You may close the issue.

--- Original Message ---

**Comment by rightx2** [comment]
What about this one? Is it ok to use  `provider.storage.get_similarities_for_object()?` in views instead of `Recommendation.objects.filter(user=user)` ?
